# Configuration for cargo-deny
# https://embarkstudios.github.io/cargo-deny/

[licenses]
# List of explicitly allowed licenses
allow = [
    "MIT",
    "Apache-2.0", 
    "Apache-2.0 WITH LLVM-exception",
    "BSD-3-Clause",
    "ISC",
    "Unicode-3.0",
    "MPL-2.0",
]

# NOTE: All licenses are denied unless explicitly allowed

# Confidence threshold for detecting a license from a license text.
confidence-threshold = 0.8

[bans]
# Lint level for when multiple versions of the same crate are detected
multiple-versions = "warn"

# Lint level for when a crate version requirement is `*`
wildcards = "allow"

# Crates that are allowed to have multiple versions
skip = [
    # Common to have multiple versions during dependency resolution
]

# Crates that are denied
deny = [
    # Add any crates you want to completely ban
]

[advisories]
# The path where the advisory database is cloned/fetched into
db-path = "~/.cargo/advisory-db"

# The url(s) of the advisory databases to use  
db-urls = ["https://github.com/rustsec/advisory-db"]

# The lint level for security vulnerabilities is handled by default

# The lint level for unmaintained crates
# unmaintained = "warn"

# The lint level for crates that have been yanked from their source registry
# yanked = "warn"

# The lint level for crates with security notices.
# notice = "warn"

# A list of advisory IDs to ignore.
ignore = [
    # Add specific advisory IDs to ignore if needed
]

[sources]
# Lint level for what to happen when a crate from a crate registry that is
# not in the allow list is encountered
unknown-registry = "warn"

# Lint level for what to happen when a crate from a git repository that is not
# in the allow list is encountered  
unknown-git = "warn"

# List of URLs for allowed crate registries. Defaults to the crates.io index
allow-registry = ["https://github.com/rust-lang/crates.io-index"]

# List of URLs for allowed Git repositories
allow-git = [] 