# Cross-compilation configuration for different targets

[target.x86_64-unknown-linux-musl]
linker = "rust-lld"

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"

# Environment variables for OpenSSL static linking
[env]
OPENSSL_STATIC = "1"

# Build settings
[build]
jobs = 4